### ISSUE TITLE
label 디렉토리와 저장 디렉토리 동일로 인한 파일 덮어쓰기로 기존 파일 없어짐

### ISSUE THREAD

**Issue by INSEA-99** [lbg030/labelconverter#1]
labelme to hubble하면 기존 라벨 파일에 덮어져서 없어져요.
저장 디렉토리 설정이나 다른 곳에 저장되면 좋겠어요.

**Comment by lbg030** [comment]
> labelme to hubble하면 기존 라벨 파일에 덮어져서 없어져요. 저장 디렉토리 설정이나 다른 곳에 저장되면 좋겠어요.

각 클래스 폴더에 hubble_json폴더를 생성해서 json파일 생성하도록 수정했습니다.
